# Generated by Django 4.1.5 on 2023-02-05 07:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to='post-images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_images', to='postapp.post')),
            ],
        ),
    ]
