# Generated by Django 4.1.5 on 2023-02-06 08:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='body',
        ),
        migrations.AddField(
            model_name='slider',
            name='description',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
